# Generated by Django 4.0.3 on 2022-04-01 10:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 1, 10, 58, 25, 33648, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
